[PGPRO-3479] Purge syncpoints of dropped node on the drop.
Or they would be still used for record filtering during receiver startup,
triggering

ERROR:  requested WAL segment pg_wal/00000001000013C900000080 has already been removed

syncpoints table is added to mtm.local_tables: this allows to preserve drop_node
going through 3pc, but make each node do cleanup of its own syncpoints in the
trigger.

(cherry picked from commit 15ef3a2804a8e3a1c2ed8cfc48d101a990a6b784)